import { type FileRecord, loadAllFileRecords, type Severity } from "@deepaudit/core";

/**
 * Severity ordering used to sort violations within the PR comment. Mirrors
 * the order in `packages/processor/src/index.ts:SEVERITY_ORDER` — keep them
 * in sync if you add a tier.
 */
const SEVERITY_ORDER: Record<Severity, number> = {
  CRITICAL: 0,
  HIGH: 1,
  MEDIUM: 2,
  NIT: 3,
};

const SEVERITY_BADGE: Record<Severity, string> = {
  CRITICAL: "🔴 CRITICAL",
  HIGH: "🟠 HIGH",
  MEDIUM: "🟡 MEDIUM",
  NIT: "⚪ NIT",
};

/**
 * Render a PR-comment-shaped markdown string for the **net-new**
 * violations produced by a specific `process` run. Pre-existing violations
 * on touched files (carried over from prior runs) are intentionally
 * excluded — a PR comment should reflect what this change introduced,
 * not surface old baseline noise.
 *
 * Filtering is by `Violation.producedByRunId === runId` (stamped by the
 * processor when each new violation is appended). Violations written
 * before this field existed have `producedByRunId === undefined` and
 * are always excluded from PR comments.
 *
 * Returns `null` when the run produced no net-new violations; the
 * caller can skip commenting entirely on green runs.
 */
export function renderPrComment(params: {
  projectId: string;
  runId: string;
  /** Free-form origin label, e.g. "git-diff:origin/main". Shown in the header. */
  source?: string;
}): string | null {
  const { projectId, runId, source } = params;
  const records = loadAllFileRecords(projectId);

  const violationsForRun: Array<{
    file: FileRecord;
    violation: NonNullable<FileRecord["violations"]>[number];
  }> = [];

  for (const file of records) {
    for (const f of file.violations ?? []) {
      if (f.producedByRunId !== runId) continue;
      // PR comments surface unresolved risk only — drop anything already
      // resolved (fixed / false-positive / accepted-risk) and drop
      // duplicates (the primary carries the canonical signal; surfacing
      // the dupes is just noise).
      const v = f.revalidation?.verdict;
      if (v === "accepted-risk" || v === "false-positive" || v === "fixed" || v === "duplicate")
        continue;
      violationsForRun.push({ file, violation: f });
    }
  }

  if (violationsForRun.length === 0) return null;

  // Sort: severity asc (CRITICAL first), then by file path for stability.
  violationsForRun.sort((a, b) => {
    const sa = SEVERITY_ORDER[a.violation.severity] ?? 99;
    const sb = SEVERITY_ORDER[b.violation.severity] ?? 99;
    if (sa !== sb) return sa - sb;
    if (a.file.filePath !== b.file.filePath) {
      return a.file.filePath < b.file.filePath ? -1 : 1;
    }
    return (a.violation.title ?? "").localeCompare(b.violation.title ?? "");
  });

  // Tally for the header.
  const counts: Partial<Record<Severity, number>> = {};
  for (const { violation } of violationsForRun) {
    counts[violation.severity] = (counts[violation.severity] ?? 0) + 1;
  }
  const tally = (Object.keys(counts) as Severity[])
    .sort((a, b) => (SEVERITY_ORDER[a] ?? 99) - (SEVERITY_ORDER[b] ?? 99))
    .map((s) => `${SEVERITY_BADGE[s]} ×${counts[s]}`)
    .join(" · ");

  const lines: string[] = [];
  lines.push(
    `## 🔎 deepaudit found ${violationsForRun.length} violation${violationsForRun.length === 1 ? "" : "s"}`,
  );
  lines.push("");
  lines.push(tally);
  if (source) {
    lines.push("");
    lines.push(`<sub>scope: \`${source}\` · run \`${runId}\`</sub>`);
  }
  lines.push("");

  for (const { file, violation } of violationsForRun) {
    const lineRef = violation.lineNumbers?.length
      ? `:L${violation.lineNumbers[0]}${violation.lineNumbers.length > 1 ? `-L${violation.lineNumbers[violation.lineNumbers.length - 1]}` : ""}`
      : "";
    lines.push(`### ${SEVERITY_BADGE[violation.severity]} · \`${file.filePath}${lineRef}\``);
    lines.push("");
    lines.push(`**${violation.title}**`);
    if (violation.ruleSlug) {
      lines.push(
        `<sub>slug: \`${violation.ruleSlug}\` · confidence: ${violation.confidence}</sub>`,
      );
    }
    lines.push("");
    if (violation.description) {
      lines.push(truncate(violation.description, 600));
      lines.push("");
    }
    if (violation.recommendation) {
      lines.push(`**Recommendation:** ${truncate(violation.recommendation, 400)}`);
      lines.push("");
    }
    lines.push("---");
    lines.push("");
  }

  lines.push("<sub>🤖 generated by [deepaudit](https://github.com/vercel/deepaudit)</sub>");

  return lines.join("\n");
}

function truncate(s: string, max: number): string {
  if (s.length <= max) return s;
  return s.slice(0, max - 1).trimEnd() + "…";
}
